language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 2.3.1
gemfile:
  - Gemfile
notifications:
  email: true
before_script:
  - nvm install 5.0
  - npm install inky-cli@^1.0.1
  - npm install promise
